name: build
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
        with:
          ref: ${{ github.ref }}

      - name: Prepare repository
        run: git checkout "${GITHUB_REF:11}"

      - name: Install Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.13.1

      - name: build
        run: make
